export const CHANGE_SELECTED_CATEGORY = 'CHANGE_SELECTED_CATEGORY'
export const CHANGE_TERMINALID = 'CHANGE_TERMINALID'
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE'
